[package]
name = "helper"
version = "0.1.0"
authors = ["Luc Veldhuis <laserluc@live.nl>"]
edition = "2018"

[dependencies]
angora_common = { path = "../common" }
bincode = "1.0"
byteorder = "1.2"
serde_json = "1.0"